from typing import List, Dict

# Structured data: rank, full name, domain for each QS top-150 university.
# Some ranks are shared (ties), resulting in 152 entries.
QS_150_schools: List[Dict] = [
    {"rank": 1,   "name": "Massachusetts Institute of Technology (MIT)",                    "domain": "mit.edu"},
    {"rank": 2,   "name": "Imperial College London",                                       "domain": "imperial.ac.uk"},
    {"rank": 2,   "name": "Stanford University",                                           "domain": "stanford.edu"},
    {"rank": 4,   "name": "University of Oxford",                                          "domain": "ox.ac.uk"},
    {"rank": 5,   "name": "Harvard University",                                            "domain": "harvard.edu"},
    {"rank": 6,   "name": "University of Cambridge",                                       "domain": "cam.ac.uk"},
    {"rank": 7,   "name": "California Institute of Technology (Caltech)",                   "domain": "caltech.edu"},
    {"rank": 8,   "name": "ETH Zurich",                                                    "domain": "ethz.ch"},
    {"rank": 8,   "name": "UCL",                                                           "domain": "ucl.ac.uk"},
    {"rank": 10,  "name": "National University of Singapore (NUS)",                         "domain": "nus.edu.sg"},
    {"rank": 11,  "name": "The University of Hong Kong",                                   "domain": "hku.hk"},
    {"rank": 12,  "name": "Nanyang Technological University, Singapore (NTU Singapore)",    "domain": "ntu.edu.sg"},
    {"rank": 13,  "name": "Peking University",                                             "domain": "pku.edu.cn"},
    {"rank": 14,  "name": "Tsinghua University",                                           "domain": "tsinghua.edu.cn"},
    {"rank": 15,  "name": "University of Pennsylvania",                                    "domain": "upenn.edu"},
    {"rank": 16,  "name": "Cornell University",                                            "domain": "cornell.edu"},
    {"rank": 16,  "name": "Yale University",                                               "domain": "yale.edu"},
    {"rank": 18,  "name": "The Chinese University of Hong Kong (CUHK)",                    "domain": "cuhk.edu.hk"},
    {"rank": 19,  "name": "The University of New South Wales (UNSW Sydney)",                "domain": "unsw.edu.au"},
    {"rank": 20,  "name": "Johns Hopkins University",                                      "domain": "jhu.edu"},
    {"rank": 20,  "name": "University of California, Berkeley (UCB)",                      "domain": "berkeley.edu"},
    {"rank": 22,  "name": "EPFL - Ecole polytechnique federale de Lausanne",               "domain": "epfl.ch"},
    {"rank": 22,  "name": "The University of Melbourne",                                   "domain": "unimelb.edu.au"},
    {"rank": 24,  "name": "University of Chicago",                                         "domain": "uchicago.edu"},
    {"rank": 25,  "name": "Technical University of Munich",                                "domain": "tum.de"},
    {"rank": 26,  "name": "Fudan University",                                              "domain": "fudan.edu.cn"},
    {"rank": 27,  "name": "Princeton University",                                          "domain": "princeton.edu"},
    {"rank": 28,  "name": "The University of Sydney",                                      "domain": "sydney.edu.au"},
    {"rank": 29,  "name": "Australian National University (ANU)",                          "domain": "anu.edu.au"},
    {"rank": 30,  "name": "McGill University",                                             "domain": "mcgill.ca"},
    {"rank": 31,  "name": "Monash University",                                             "domain": "monash.edu"},
    {"rank": 32,  "name": "University of Toronto",                                         "domain": "utoronto.ca"},
    {"rank": 33,  "name": "The Hong Kong University of Science and Technology",             "domain": "hkust.edu.hk"},
    {"rank": 34,  "name": "Universite PSL",                                                "domain": "psl.eu"},
    {"rank": 35,  "name": "The University of Edinburgh",                                   "domain": "ed.ac.uk"},
    {"rank": 36,  "name": "Shanghai Jiao Tong University",                                 "domain": "sjtu.edu.cn"},
    {"rank": 37,  "name": "King's College London",                                         "domain": "kcl.ac.uk"},
    {"rank": 38,  "name": "Seoul National University",                                     "domain": "snu.ac.kr"},
    {"rank": 39,  "name": "The University of Tokyo",                                       "domain": "u-tokyo.ac.jp"},
    {"rank": 40,  "name": "The University of Manchester",                                  "domain": "manchester.ac.uk"},
    {"rank": 40,  "name": "The University of Queensland",                                  "domain": "uq.edu.au"},
    {"rank": 42,  "name": "Yonsei University",                                             "domain": "yonsei.ac.kr"},
    {"rank": 43,  "name": "Columbia University",                                           "domain": "columbia.edu"},
    {"rank": 43,  "name": "Institut Polytechnique de Paris",                               "domain": "ip-paris.fr"},
    {"rank": 45,  "name": "Northwestern University",                                       "domain": "northwestern.edu"},
    {"rank": 45,  "name": "University of British Columbia",                                "domain": "ubc.ca"},
    {"rank": 47,  "name": "Zhejiang University",                                           "domain": "zju.edu.cn"},
    {"rank": 48,  "name": "Delft University of Technology",                                "domain": "tudelft.nl"},
    {"rank": 49,  "name": "University of California, Los Angeles (UCLA)",                  "domain": "ucla.edu"},
    {"rank": 50,  "name": "The Hong Kong Polytechnic University",                          "domain": "polyu.edu.hk"},
    {"rank": 51,  "name": "University of Michigan-Ann Arbor",                              "domain": "umich.edu"},
    {"rank": 52,  "name": "City University of Hong Kong (CityUHK)",                        "domain": "cityu.edu.hk"},
    {"rank": 52,  "name": "Korea University",                                              "domain": "korea.ac.kr"},
    {"rank": 54,  "name": "National Taiwan University (NTU)",                              "domain": "ntu.edu.tw"},
    {"rank": 55,  "name": "Carnegie Mellon University",                                    "domain": "cmu.edu"},
    {"rank": 56,  "name": "Universiti Malaya (UM)",                                        "domain": "um.edu.my"},
    {"rank": 57,  "name": "University of Bristol",                                         "domain": "bristol.ac.uk"},
    {"rank": 58,  "name": "New York University (NYU)",                                     "domain": "nyu.edu"},
    {"rank": 59,  "name": "KU Leuven",                                                     "domain": "kuleuven.be"},
    {"rank": 60,  "name": "University of Amsterdam",                                       "domain": "uva.nl"},
    {"rank": 61,  "name": "Ludwig-Maximilians-Universitaet Muenchen",                      "domain": "lmu.de"},
    {"rank": 62,  "name": "The London School of Economics and Political Science (LSE)",     "domain": "lse.ac.uk"},
    {"rank": 63,  "name": "KFUPM",                                                         "domain": "kfupm.edu.sa"},
    {"rank": 64,  "name": "Kyoto University",                                              "domain": "kyoto-u.ac.jp"},
    {"rank": 65,  "name": "KAIST",                                                         "domain": "kaist.ac.kr"},
    {"rank": 66,  "name": "Brown University",                                              "domain": "brown.edu"},
    {"rank": 67,  "name": "The University of Auckland",                                    "domain": "auckland.ac.nz"},
    {"rank": 68,  "name": "The University of Warwick",                                     "domain": "warwick.ac.uk"},
    {"rank": 68,  "name": "University of Birmingham",                                      "domain": "birmingham.ac.uk"},
    {"rank": 70,  "name": "Duke University",                                               "domain": "duke.edu"},
    {"rank": 71,  "name": "Lund University",                                               "domain": "lu.se"},
    {"rank": 72,  "name": "University of Texas at Austin",                                 "domain": "utexas.edu"},
    {"rank": 73,  "name": "Sorbonne University",                                           "domain": "sorbonne-universite.fr"},
    {"rank": 74,  "name": "University of Illinois Urbana-Champaign",                       "domain": "illinois.edu"},
    {"rank": 75,  "name": "Trinity College Dublin, The University of Dublin",               "domain": "tcd.ie"},
    {"rank": 76,  "name": "Universite Paris-Saclay",                                       "domain": "universite-paris-saclay.fr"},
    {"rank": 77,  "name": "The University of Western Australia",                           "domain": "uwa.edu.au"},
    {"rank": 77,  "name": "University of Leeds",                                           "domain": "leeds.ac.uk"},
    {"rank": 79,  "name": "Adelaide University",                                           "domain": "adelaide.edu.au"},
    {"rank": 80,  "name": "University of Glasgow",                                         "domain": "gla.ac.uk"},
    {"rank": 81,  "name": "University of California, San Diego (UCSD)",                    "domain": "ucsd.edu"},
    {"rank": 82,  "name": "KTH Royal Institute of Technology",                             "domain": "kth.se"},
    {"rank": 82,  "name": "The University of Sheffield",                                   "domain": "sheffield.ac.uk"},
    {"rank": 84,  "name": "Universidad de Buenos Aires (UBA)",                             "domain": "uba.ar"},
    {"rank": 85,  "name": "Durham University",                                             "domain": "durham.ac.uk"},
    {"rank": 86,  "name": "Universitaet Heidelberg",                                       "domain": "uni-heidelberg.de"},
    {"rank": 87,  "name": "Politecnico di Milano",                                         "domain": "polimi.it"},
    {"rank": 87,  "name": "University of Technology Sydney",                               "domain": "uts.edu.au"},
    {"rank": 87,  "name": "Uppsala University",                                            "domain": "uu.se"},
    {"rank": 90,  "name": "Nanjing University",                                            "domain": "nju.edu.cn"},
    {"rank": 90,  "name": "University of Copenhagen",                                      "domain": "ku.dk"},
    {"rank": 92,  "name": "Pennsylvania State University",                                 "domain": "psu.edu"},
    {"rank": 92,  "name": "University of Washington",                                      "domain": "washington.edu"},
    {"rank": 94,  "name": "Boston University",                                             "domain": "bu.edu"},
    {"rank": 95,  "name": "The University of Osaka",                                       "domain": "osaka-u.ac.jp"},
    {"rank": 96,  "name": "University of Alberta",                                         "domain": "ualberta.ca"},
    {"rank": 97,  "name": "Institute of Science Tokyo",                                    "domain": "isct.ac.jp"},
    {"rank": 97,  "name": "University of Nottingham",                                      "domain": "nottingham.ac.uk"},
    {"rank": 98,  "name": "Freie Universitaet Berlin",                                     "domain": "fu-berlin.de"},
    {"rank": 98,  "name": "University of Zurich",                                          "domain": "uzh.ch"},
    {"rank": 100, "name": "Purdue University",                                             "domain": "purdue.edu"},
    {"rank": 100, "name": "University College Dublin",                                     "domain": "ucd.ie"},
    {"rank": 102, "name": "Tohoku University",                                             "domain": "tohoku.ac.jp"},
    {"rank": 103, "name": "Queen Mary University of London",                               "domain": "qmul.ac.uk"},
    {"rank": 104, "name": "RWTH Aachen University",                                       "domain": "rwth-aachen.de"},
    {"rank": 105, "name": "Technical University of Denmark",                               "domain": "dtu.dk"},
    {"rank": 106, "name": "Pohang University of Science And Technology (POSTECH)",          "domain": "postech.ac.kr"},
    {"rank": 107, "name": "King Saud University",                                          "domain": "ksu.edu.sa"},
    {"rank": 108, "name": "Sungkyunkwan University (SKKU)",                                "domain": "skku.edu"},
    {"rank": 109, "name": "Qatar University",                                              "domain": "qu.edu.qa"},
    {"rank": 110, "name": "KIT, Karlsruhe Institute of Technology",                        "domain": "kit.edu"},
    {"rank": 111, "name": "Sapienza University of Rome",                                   "domain": "uniroma1.it"},
    {"rank": 111, "name": "University of Southampton",                                     "domain": "southampton.ac.uk"},
    {"rank": 113, "name": "University of Waterloo",                                        "domain": "uwaterloo.ca"},
    {"rank": 113, "name": "Utrecht University",                                            "domain": "uu.nl"},
    {"rank": 115, "name": "Lomonosov Moscow State University",                             "domain": "msu.ru"},
    {"rank": 115, "name": "University of St Andrews",                                      "domain": "st-andrews.ac.uk"},
    {"rank": 118, "name": "Indian Institute of Technology Delhi (IITD)",                   "domain": "iitd.ac.in"},
    {"rank": 119, "name": "Leiden University",                                             "domain": "leidenuniv.nl"},
    {"rank": 119, "name": "Pontificia Universidad Catolica de Chile (UC)",                 "domain": "uc.cl"},
    {"rank": 119, "name": "RMIT University",                                               "domain": "rmit.edu.au"},
    {"rank": 122, "name": "Rice University",                                               "domain": "rice.edu"},
    {"rank": 123, "name": "Alma Mater Studiorum - Universita di Bologna",                  "domain": "unibo.it"},
    {"rank": 123, "name": "University of Helsinki",                                        "domain": "helsinki.fi"},
    {"rank": 125, "name": "University of Bath",                                            "domain": "bath.ac.uk"},
    {"rank": 126, "name": "Aalto University",                                              "domain": "aalto.fi"},
    {"rank": 126, "name": "Macquarie University (Sydney, Australia)",                      "domain": "mq.edu.au"},
    {"rank": 128, "name": "Aarhus University",                                             "domain": "au.dk"},
    {"rank": 128, "name": "Universiti Sains Malaysia (USM)",                               "domain": "usm.my"},
    {"rank": 130, "name": "Universiti Kebangsaan Malaysia (UKM)",                          "domain": "ukm.edu.my"},
    {"rank": 131, "name": "University of Oslo",                                            "domain": "uio.no"},
    {"rank": 131, "name": "University of Wisconsin-Madison",                               "domain": "wisc.edu"},
    {"rank": 133, "name": "Universidade de Sao Paulo",                                     "domain": "usp.br"},
    {"rank": 134, "name": "Indian Institute of Technology Bombay (IITB)",                  "domain": "iitb.ac.in"},
    {"rank": 134, "name": "University of Science and Technology of China",                 "domain": "ustc.edu.cn"},
    {"rank": 136, "name": "University of Exeter",                                          "domain": "exeter.ac.uk"},
    {"rank": 137, "name": "University of California, Davis",                               "domain": "ucdavis.edu"},
    {"rank": 138, "name": "Universiti Putra Malaysia (UPM)",                               "domain": "upm.edu.my"},
    {"rank": 139, "name": "University of Liverpool",                                       "domain": "liverpool.ac.uk"},
    {"rank": 140, "name": "Humboldt-Universitaet zu Berlin",                               "domain": "hu-berlin.de"},
    {"rank": 140, "name": "University of Vienna",                                          "domain": "univie.ac.at"},
    {"rank": 142, "name": "Georgia Institute of Technology",                               "domain": "gatech.edu"},
    {"rank": 142, "name": "National Tsing Hua University - NTHU",                          "domain": "nthu.edu.tw"},
    {"rank": 142, "name": "Western University",                                            "domain": "uwo.ca"},
    {"rank": 145, "name": "Universidad Nacional Autonoma de Mexico (UNAM)",                "domain": "unam.mx"},
    {"rank": 146, "name": "Tongji University",                                             "domain": "tongji.edu.cn"},
    {"rank": 147, "name": "Khalifa University",                                            "domain": "ku.ac.ae"},
    {"rank": 148, "name": "Erasmus University Rotterdam",                                  "domain": "eur.nl"},
    {"rank": 149, "name": "Newcastle University",                                          "domain": "ncl.ac.uk"},
    {"rank": 150, "name": "Ghent University",                                              "domain": "ugent.be"},
    {"rank": 150, "name": "University of Basel",                                           "domain": "unibas.ch"},
]

# Backward-compatible flat domain list (used by school_searcher.py TavilySearch)
QS_150_list: List[str] = [s["domain"] for s in QS_150_schools]
