package com.example.frontend.ui.theme

import androidx.compose.ui.graphics.Color

// 静谧靛蓝 (Serene Indigo) — light scheme
val PrimaryLight = Color(0xFF3A5BA0)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFDCE6FA)
val OnPrimaryContainerLight = Color(0xFF10233F)
val SecondaryLight = Color(0xFFF2A65A)
val OnSecondaryLight = Color(0xFF3A2A12)
val SecondaryContainerLight = Color(0xFFFCE3C6)
val OnSecondaryContainerLight = Color(0xFF3A2A12)
val TertiaryLight = Color(0xFF5C6B90)
val OnTertiaryLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFF7F8FC)
val OnBackgroundLight = Color(0xFF1C1E26)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF1C1E26)
val SurfaceVariantLight = Color(0xFFEDEFF5)
val OnSurfaceVariantLight = Color(0xFF5F6880)
val OutlineLight = Color(0xFFC9D0E0)
val SuccessLight = Color(0xFF2E7D32)
val OnSuccessLight = Color(0xFFFFFFFF)

// 静谧靛蓝 — dark scheme
val PrimaryDark = Color(0xFFA9C1F0)
val OnPrimaryDark = Color(0xFF12233F)
val PrimaryContainerDark = Color(0xFF25417A)
val OnPrimaryContainerDark = Color(0xFFDCE6FA)
val SecondaryDark = Color(0xFFF2B876)
val OnSecondaryDark = Color(0xFF3A2A12)
val SecondaryContainerDark = Color(0xFF5A4322)
val OnSecondaryContainerDark = Color(0xFFFCE3C6)
val TertiaryDark = Color(0xFFAAB8DC)
val OnTertiaryDark = Color(0xFF1C2540)
val BackgroundDark = Color(0xFF12141C)
val OnBackgroundDark = Color(0xFFE7E9F2)
val SurfaceDark = Color(0xFF1B1E29)
val OnSurfaceDark = Color(0xFFE7E9F2)
val SurfaceVariantDark = Color(0xFF2A2E3B)
val OnSurfaceVariantDark = Color(0xFF9AA3B8)
val OutlineDark = Color(0xFF4A5266)
val SuccessDark = Color(0xFF7FCF81)
val OnSuccessDark = Color(0xFF0D2A0E)